import pandas as pd

def safe_int(val):
    return int(val) if pd.notna(val) else 0

def calculate_sweepstake_metrics():
    try:
        team_stats = pd.read_csv('data/team_stats_2026.csv')
        players = pd.read_csv('data/sweepstakeplayers.csv')
        matches = pd.read_csv('data/matches_2026.csv')
        
        # Merge player data with the stats generated by transform.py
        merged = pd.merge(players, team_stats, on='Team', how='left').fillna(0)
        
        # Apply Ironclad Tie-Breakers via Multi-Column Sorting
        most_goals_winner = merged.sort_values(by=['goals_scored', 'goals_conceded'], ascending=[False, True]).iloc[0]
        most_conceded_winner = merged.sort_values(by=['goals_conceded', 'goals_scored'], ascending=[False, False]).iloc[0]
        most_draws_winner = merged.sort_values(by=['draws', 'draw_goals_scored'], ascending=[False, False]).iloc[0]
        
        # Calculate Biggest Upset
        team_to_player = dict(zip(players['Team'], players['Name']))
        team_to_rank = dict(zip(players['Team'], players['FIFA_Rank_(Jun26)']))
        
        biggest_upset_record = None
        max_rank_diff = -999  
        
        finished_matches = matches[matches['status'] == 'FINISHED']
        
        for _, match in finished_matches.iterrows():
            home, away, winner = match['home_team'], match['away_team'], match['winner']
            
            if home not in team_to_rank or away not in team_to_rank:
                continue
                
            home_rank, away_rank = team_to_rank[home], team_to_rank[away]
            h_score_str, a_score_str = safe_int(match['home_score']), safe_int(match['away_score'])
            
            if winner == 'HOME_TEAM':
                diff = home_rank - away_rank
                if diff > max_rank_diff:
                    max_rank_diff = diff
                    biggest_upset_record = {
                        'winner_team': home, 'winner_player': team_to_player[home],
                        'loser_team': away, 'loser_player': team_to_player[away],
                        'score': f"{h_score_str} - {a_score_str}", 'diff': diff
                    }
            elif winner == 'AWAY_TEAM':
                diff = away_rank - home_rank
                if diff > max_rank_diff:
                    max_rank_diff = diff
                    biggest_upset_record = {
                        'winner_team': away, 'winner_player': team_to_player[away],
                        'loser_team': home, 'loser_player': team_to_player[home],
                        'score': f"{a_score_str} - {h_score_str}", 'diff': diff
                    }
                    
        return {
            "most_goals": most_goals_winner, "most_conceded": most_conceded_winner,
            "most_draws": most_draws_winner, "biggest_upset": biggest_upset_record,
            "master_data": merged  
        }
    except Exception as e:
        print(f"Metrics Engine Error: {e}")
        return None